name: Validate the PR code
description: These jobs ensure that the code in the PR is formatted correctly and builds successfully.
on:
  pull_request:
    branches:
      - main

jobs:
  validate-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: '20'
      - name: Install prettier
        run: npm install -g prettier
      - name: Validate formatting
        run: prettier --check .
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install -g yarn && yarn install
      - name: Build project
        run: yarn build
